function displayData(adjective, measuredValues)
%DISPLAYDATA fprints vector in form of [rNorm, vNorm, orbitalElements]

fprintf(['-------------------\n%s parameters:\n' ...
    'R(2): %.2f km \n' ...
    'V(2): %.2f km/s \n' ...
    'specific angular momentum: %.2f km^2/s \n' ...
    'inclination: %.4f rad \n' ...
    'RA of ascending node: %.4f rad \n' ...
    'eccentricity: %f  \n' ...
    'perigee argument: %.4f rad \n' ...
    'true anomaly(2): %.4f rad \n-------------------\n'], ...
    adjective, measuredValues);

end

