function displayData(adjective, measuredValues)
%DISPLAYDATA fprints vector in form of [rNorm, vNorm, orbitalElements]

fprintf(['-------------------\n%s parameters:\n' ...
    'R(2): %.2g km \n' ...
    'V(2): %.2g km/s \n' ...
    'specific angular momentum: %.2g km^2/s \n' ...
    'inclination: %.4g rad \n' ...
    'RA of ascending node: %.4g rad \n' ...
    'eccentricity: %g  \n' ...
    'perigee argument: %.4g rad \n' ...
    'true anomaly(2): %.4g rad \n-------------------\n'], ...
    adjective, measuredValues);

end

