function displayData(adjective, measuredValues)
%DISPLAYDATA fprints vector in form of [rNorm, vNorm, orbitalElements]

% rad2deg
deg = 180/pi;
measuredValues(4) = measuredValues(4) * deg;
measuredValues(5) = measuredValues(5) * deg;
measuredValues(7) = measuredValues(7) * deg;
measuredValues(8) = measuredValues(8) * deg;

fprintf(['-------------------\n%s parameters:\n' ...
    'R(2): %g km \n' ...
    'V(2): %.2g km/s \n' ...
    'semimajor axis: %g km \n' ...
    'inclination: %.4g deg \n' ...
    'RA of ascending node: %.4g deg \n' ...
    'eccentricity: %g  \n' ...
    'perigee argument: %.4g deg \n' ...
    'true anomaly(2): %.4g deg \n-------------------\n'], ...
    adjective, measuredValues);

end

